import { NextResponse } from "next/server";

import attestationData from "@/lib/attestation-data.json";
import { prisma } from "@/lib/db";
import { EMBEDDING_DIM, EMBEDDING_MODEL } from "@/lib/gemini";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Attestation endpoint — single-curl audit-survivability probe.
 *
 * Recorded in [ADR-0056]. Companion to:
 *   - `scripts/check-doc-drift.mjs` (Pattern A — assert claims at PR
 *     time)
 *   - `GET /api/health/schema` (ADR-0053 — runtime schema canary)
 *
 * The doc-drift-detect CI gate (ADR-0054) catches stale numerics in
 * markdown / TSX prose at PR time. The schema canary catches
 * runtime-vs-PR-time db divergence. This endpoint is the third leg of
 * the audit-survivability tripod: a **single live URL** that exposes
 * everything a senior reviewer would otherwise have to assemble from
 * `gh api` + `git log` + `curl /api/kb/stats` + `curl /api/health/schema`
 * + reading 5 markdown files. Run as:
 *
 *     curl https://craftstack-knowledge.vercel.app/api/attestation | jq
 *
 * Build-time invariants (tag, commit, adrCount, boardlyRouteCount,
 * lastEvalRun, deferred features, honest scope notes) come from
 * `apps/knowledge/src/lib/attestation-data.json`, generated by
 * `scripts/generate-attestation-data.mjs` during `vercel-build`.
 *
 * Runtime augmentation (schema drift, corpus stats, latestMigration,
 * daysSinceLastGreenRun, cronHealthHint) is computed per-request so
 * the endpoint reflects the live db state at probe time. `force-dynamic`
 * + `cache-control: no-store` so a CDN cannot serve a stale snapshot.
 *
 * The `cronHealthHint` field implements the threat-model T-06
 * mitigation: surfaces "last green eval was N days ago" separately
 * from the README badge, which by design stays at last-green-state
 * (not last-cron-state) per ADR-0049 § 7th arc Tier C-#2 + § 8th arc.
 */

type LatestMigration = { name: string; appliedAt: string } | null;
type SchemaCheck = {
  table: string;
  expected: string[];
  actual: string[];
  missing: string[];
  drift: boolean;
};

// Mirror the EXPECTED constant from /api/health/schema/route.ts.
// `expected.test.ts` (ADR-0053) keeps that constant in sync with
// `prisma/schema.prisma`. We re-state here rather than import so the
// attestation endpoint stays self-contained against route refactors;
// the cost is a single extra place to maintain, asserted by the same
// test pattern.
const EXPECTED_SCHEMA = {
  Workspace: ["id", "name", "slug", "createdAt"],
  Document: [
    "id",
    "workspaceId",
    "title",
    "content",
    "charCount",
    "createdAt",
    "updatedAt",
  ],
  Chunk: ["id", "documentId", "ordinal", "content", "tokenCount", "createdAt"],
  Embedding: ["chunkId", "model", "dim", "embedding", "createdAt"],
} as const;

async function probeSchema(): Promise<{
  drift: boolean;
  latestMigration: LatestMigration;
  checks: SchemaCheck[];
}> {
  const tables = Object.keys(EXPECTED_SCHEMA);
  const actualRows = await prisma.$queryRawUnsafe<
    Array<{ table_name: string; column_name: string }>
  >(
    `SELECT table_name, column_name
       FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = ANY($1::text[])
      ORDER BY table_name, ordinal_position`,
    tables,
  );
  const actualByTable = new Map<string, string[]>();
  for (const r of actualRows) {
    if (!actualByTable.has(r.table_name)) actualByTable.set(r.table_name, []);
    actualByTable.get(r.table_name)!.push(r.column_name);
  }
  const checks: SchemaCheck[] = [];
  let anyDrift = false;
  for (const [table, expected] of Object.entries(EXPECTED_SCHEMA)) {
    const actual = actualByTable.get(table) ?? [];
    const missing = (expected as readonly string[]).filter(
      (c) => !actual.includes(c),
    );
    const drift = missing.length > 0;
    if (drift) anyDrift = true;
    checks.push({
      table,
      expected: [...(expected as readonly string[])],
      actual,
      missing,
      drift,
    });
  }
  let latestMigration: LatestMigration = null;
  try {
    const rows = await prisma.$queryRawUnsafe<
      Array<{ migration_name: string; finished_at: Date | null }>
    >(
      `SELECT migration_name, finished_at FROM "_prisma_migrations"
        WHERE finished_at IS NOT NULL
        ORDER BY finished_at DESC
        LIMIT 1`,
    );
    if (rows[0] && rows[0].finished_at) {
      latestMigration = {
        name: rows[0].migration_name,
        appliedAt: rows[0].finished_at.toISOString(),
      };
    }
  } catch {
    // best-effort
  }
  return { drift: anyDrift, latestMigration, checks };
}

async function probeCorpus() {
  const [documents, chunks, embeddings, idxRows, dimRows] = await Promise.all([
    prisma.document.count(),
    prisma.chunk.count(),
    prisma.embedding.count(),
    prisma.$queryRawUnsafe<Array<{ amname: string | null }>>(
      `SELECT am.amname
         FROM pg_class      c
         JOIN pg_index      i  ON i.indexrelid = c.oid
         JOIN pg_am         am ON am.oid = c.relam
        WHERE c.relname = 'Embedding_embedding_cosine_idx'
        LIMIT 1`,
    ),
    prisma.$queryRawUnsafe<Array<{ stored_dim: number | null }>>(
      `SELECT MAX(vector_dims("embedding"))::int AS stored_dim FROM "Embedding"`,
    ),
  ]);
  return {
    documents,
    chunks,
    embeddings,
    indexType: idxRows[0]?.amname ?? null,
    storedDim: dimRows[0]?.stored_dim ?? null,
    expectedDim: EMBEDDING_DIM,
    embeddingModel: EMBEDDING_MODEL,
  };
}

function staleness(lastEvalRunAt: string | null | undefined): {
  daysSinceLastGreenRun: number | null;
  cronHealthHint: string;
} {
  if (!lastEvalRunAt) {
    return {
      daysSinceLastGreenRun: null,
      cronHealthHint:
        "no green eval run on record — first measurement pending or all recent runs failed",
    };
  }
  const ms = Date.now() - new Date(lastEvalRunAt).getTime();
  const days = ms / (1000 * 60 * 60 * 24);
  let hint: string;
  if (days < 1.5) {
    hint = "fresh (last green run within 36h)";
  } else if (days < 3) {
    hint =
      "stale: last green run >36h ago — eval workflow may be failing on recent crons (T-06)";
  } else {
    hint =
      "very stale: last green run >3 days ago — investigate the eval workflow status before trusting the badge (T-06)";
  }
  return {
    daysSinceLastGreenRun: Number(days.toFixed(2)),
    cronHealthHint: hint,
  };
}

export async function GET() {
  const [schema, corpus] = await Promise.all([probeSchema(), probeCorpus()]);
  const { daysSinceLastGreenRun, cronHealthHint } = staleness(
    attestationData.measurements.lastEvalRun?.ranAt,
  );

  return NextResponse.json(
    {
      ...attestationData,
      runtime: {
        schema: {
          drift: schema.drift,
          latestMigration: schema.latestMigration,
          checks: schema.checks,
        },
        corpus,
      },
      measurements: {
        ...attestationData.measurements,
        daysSinceLastGreenRun,
        cronHealthHint,
      },
      probedAt: new Date().toISOString(),
    },
    {
      status: schema.drift ? 503 : 200,
      headers: { "cache-control": "no-store" },
    },
  );
}
