name: data_analytics_demo
version: 0.1.0
config-version: 2

profile: data_analytics_demo

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  data_analytics_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
